# Generated by Django 5.0.6 on 2024-07-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GreetingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('greeting_text', models.TextField()),
                ('image_path', models.CharField(max_length=255)),
            ],
        ),
    ]
